apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsexamapp
  namespace: devopsexamapp
  labels:
    app: devopsexamapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsexamapp
  template:
    metadata:
      labels:
        app: devopsexamapp
    spec:
      containers:
      - name: devopsexamapp
        image: mhn98/devopsexamapp1:latest  # This gets replaced dynamically in Jenkinsfile
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhub-creds
